/* tslint:disable */
/* eslint-disable */
/**
 * code-with-quarkus API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Dog
 */
export interface Dog {
    /**
     * 
     * @type {number}
     * @memberof Dog
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Dog
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Dog
     */
    race?: string;
    /**
     * 
     * @type {number}
     * @memberof Dog
     */
    weight?: number;
    /**
     * 
     * @type {number}
     * @memberof Dog
     */
    ownerId?: number;
}

/**
 * Check if a given object implements the Dog interface.
 */
export function instanceOfDog(value: object): value is Dog {
    return true;
}

export function DogFromJSON(json: any): Dog {
    return DogFromJSONTyped(json, false);
}

export function DogFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dog {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'race': json['race'] == null ? undefined : json['race'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
    };
}

export function DogToJSON(value?: Dog | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'race': value['race'],
        'weight': value['weight'],
        'owner_id': value['ownerId'],
    };
}

