/* tslint:disable */
/* eslint-disable */
/**
 * code-with-quarkus API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceUpdate
 */
export interface InvoiceUpdate {
    /**
     * 
     * @type {string}
     * @memberof InvoiceUpdate
     */
    identifier?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceUpdate
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceUpdate
     */
    locale?: string;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceUpdate
     */
    date?: Date;
}

/**
 * Check if a given object implements the InvoiceUpdate interface.
 */
export function instanceOfInvoiceUpdate(value: object): value is InvoiceUpdate {
    return true;
}

export function InvoiceUpdateFromJSON(json: any): InvoiceUpdate {
    return InvoiceUpdateFromJSONTyped(json, false);
}

export function InvoiceUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'identifier': json['identifier'] == null ? undefined : json['identifier'],
        'text': json['text'] == null ? undefined : json['text'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
    };
}

export function InvoiceUpdateToJSON(value?: InvoiceUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'identifier': value['identifier'],
        'text': value['text'],
        'locale': value['locale'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString().substring(0,10)),
    };
}

