/* tslint:disable */
/* eslint-disable */
/**
 * code-with-quarkus API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Tax
 */
export interface Tax {
    /**
     * 
     * @type {number}
     * @memberof Tax
     */
    taxRate?: number;
    /**
     * 
     * @type {number}
     * @memberof Tax
     */
    taxTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof Tax
     */
    taxAmount?: number;
}

/**
 * Check if a given object implements the Tax interface.
 */
export function instanceOfTax(value: object): value is Tax {
    return true;
}

export function TaxFromJSON(json: any): Tax {
    return TaxFromJSONTyped(json, false);
}

export function TaxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tax {
    if (json == null) {
        return json;
    }
    return {
        
        'taxRate': json['tax_rate'] == null ? undefined : json['tax_rate'],
        'taxTotal': json['tax_total'] == null ? undefined : json['tax_total'],
        'taxAmount': json['tax_amount'] == null ? undefined : json['tax_amount'],
    };
}

export function TaxToJSON(value?: Tax | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tax_rate': value['taxRate'],
        'tax_total': value['taxTotal'],
        'tax_amount': value['taxAmount'],
    };
}

