/* tslint:disable */
/* eslint-disable */
/**
 * code-with-quarkus API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Who
 */
export interface Who {
    /**
     * 
     * @type {string}
     * @memberof Who
     */
    vorName?: string;
    /**
     * 
     * @type {string}
     * @memberof Who
     */
    nachName?: string;
}

/**
 * Check if a given object implements the Who interface.
 */
export function instanceOfWho(value: object): value is Who {
    return true;
}

export function WhoFromJSON(json: any): Who {
    return WhoFromJSONTyped(json, false);
}

export function WhoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Who {
    if (json == null) {
        return json;
    }
    return {
        
        'vorName': json['vor_name'] == null ? undefined : json['vor_name'],
        'nachName': json['nach_name'] == null ? undefined : json['nach_name'],
    };
}

export function WhoToJSON(value?: Who | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'vor_name': value['vorName'],
        'nach_name': value['nachName'],
    };
}

